sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockernagbattula/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockernagbattula/react-test npm test

after_success:
  - docker build -t dockernagbattula/multi-client ./client
  - docker build -t dockernagbattula/multi-nginx ./nginx
  - docker build -t dockernagbattula/multi-server ./server
  - docker build -t dockernagbattula/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockernagbattula/multi-client
  - docker push dockernagbattula/multi-nginx
  - docker push dockernagbattula/multi-server
  - docker push dockernagbattula/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-705597486007"
  bucket_path: "docker-multi"
  on:
    branches: # ← new!
      only: # ← new!
        - master # ← new!
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
